openapi: 3.0.0
info:
  title: 'Calendar App'
  description: 'This API is designed to facilitate the management of a comprehensive calendar application, encompassing a broad range of functionalities including user management, event scheduling, course allocation, group coordination, department organization, and timetable structuring. It aims to provide an integrated platform for educational institutions to efficiently organize and access academic and administrative information.'
  version: 1.0.3
servers:
  -
    url: 'http://localhost/web_project/src/'
paths:
  /users:
    get:
      tags:
        - users
      summary: 'Retrieve one user by email or all users'
      description: 'Returns a single user if email is provided or all users if no email is provided.'
      operationId: 0940fc3675fe6a0a70eceb8334255fbf
      parameters:
        -
          name: email
          in: query
          description: 'The email of the user to retrieve'
          required: false
          schema:
            type: string
            format: email
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                oneOf:
                  - { description: 'List of all users', type: array, items: { $ref: '#/components/schemas/User' } }
                  - { $ref: '#/components/schemas/User' }
        '404':
          description: 'User not found'
          content:
            application/json:
              schema:
                properties:
                  code: { type: integer, example: '404' }
                  status: { type: string, example: error }
                  message: { type: string, example: 'User not found' }
                type: object
        '500':
          description: 'Internal Server Error'
components:
  schemas:
    User:
      title: User
      description: 'User entity schema'
      required:
        - id
        - email
        - firstName
        - lastName
        - type
      properties:
        id:
          description: 'Unique identifier for the user'
          type: integer
          format: int64
        email:
          description: 'User email address'
          type: string
          format: email
        firstName:
          description: "User's first name"
          type: string
        lastName:
          description: "User's last name"
          type: string
        type:
          description: 'The type of user'
          type: string
          enum:
            - student
            - teacher
            - admin
        password:
          description: 'User password, not generally returned in responses for security reasons'
          type: string
          writeOnly: true
          example: examplePassword123!
      type: object
